# 📌 NumPy Assignment

In [1]:
import numpy as np

## 1️⃣ 
Created a NumPy array with from 1 to 20 using np.arange()

In [2]:
arr_1d = np.arange(1, 21)
print("1D Array (1 to 20):", arr_1d)

1D Array (1 to 20): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### 1(a)
Calculated and printed np.sum(), np.mean(), np.median() and np.std()

In [3]:
arr_sum = np.sum(arr_1d)
arr_mean = np.mean(arr_1d)
arr_median = np.median(arr_1d)
arr_std = np.std(arr_1d)

print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Median:", arr_median)
print("Standard Deviation:", arr_std)

Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


### 1(b)
Used np.where to find out the indices of elements greater then 10

In [4]:
indices_gt_10 = np.where(arr_1d > 10)[0]
print("Indices of elements > 10:", indices_gt_10)

Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]


## 2️⃣
Created a 2D NumPy array of shape 4x4 with numbers 1 to 16 using np.arange() and .reshape()

In [5]:
arr_2d = np.arange(1, 17).reshape(4, 4)

### 2(a)
Printed the array

In [6]:
print("2D Array (4x4):\n", arr_2d)

2D Array (4x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 2(b)
Transpose of array using .T

In [7]:
arr_2d_T = arr_2d.T
print("Transpose of the array:\n", arr_2d_T)


Transpose of the array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


### 2(c)
Row and column wise sum of array using np.sum()  
axis = 1 ---> row-wise  
axis = 0 ---> column-wise

In [8]:
row_sums = np.sum(arr_2d, axis=1)
col_sums = np.sum(arr_2d, axis=0)

print("Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)


Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]


## 3️⃣
Creating two 3x3 arrays filled wwith random integers between 1 and 20 using np.random.randint()  
and setting seed for rpeatable results using np.random.seed()

In [9]:
np.random.seed(0)

A = np.random.randint(1, 21, size=(3, 3))
B = np.random.randint(1, 21, size=(3, 3))

print("Array A:\n", A)
print("Array B:\n", B)



Array A:
 [[13 16  1]
 [ 4  4  8]
 [10 20 19]]
Array B:
 [[ 5  7 13]
 [ 2  7  8]
 [15 18  6]]


### 3(a)
Did element wise addition substraction and Multiplication

In [10]:
add_result = A + B
sub_result = A - B
mul_result = A * B

print("Element-wise Addition:\n", add_result)
print("Element-wise Subtraction:\n", sub_result)
print("Element-wise Multiplication:\n", mul_result)

Element-wise Addition:
 [[18 23 14]
 [ 6 11 16]
 [25 38 25]]
Element-wise Subtraction:
 [[  8   9 -12]
 [  2  -3   0]
 [ -5   2  13]]
Element-wise Multiplication:
 [[ 65 112  13]
 [  8  28  64]
 [150 360 114]]


### 3(b)
Did dot product of the two arrays using np.dot()

In [11]:
dot_result = np.dot(A, B)
print("Dot Product (A . B):\n", dot_result)

Dot Product (A . B):
 [[112 221 303]
 [148 200 132]
 [375 552 404]]


## 4️⃣
Created an 1D array and reshaped it into a 3x4 2D array using np.reshape()

In [12]:
arr_1d_12 = np.arange(1, 13)
arr_3x4 = arr_1d_12.reshape(3, 4)
print("Original 3x4 array:\n", arr_3x4)

Original 3x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Slice the first two rows and last two columns  
First two rows -> rows with index 0 and 1 -> :2  
Last two columns -> columns with index 2 and 3 -> -2:

In [13]:
sliced_arr = arr_3x4[:2, -2:]
print("Sliced array (first 2 rows, last 2 columns):\n", sliced_arr)

Sliced array (first 2 rows, last 2 columns):
 [[3 4]
 [7 8]]
